### PR TITLE
Nixify .ssh/config using home-manager

### LINKED ISSUE #36: Nixify `.ssh/config` using home-manager
```
Host actual
  HostName 167.205.125.179
  ForwardAgent yes

Host biryani
  User admin
  HostName 100.97.32.60
  ForwardAgent yes

# To clone Juspay repos.
# https://developer.1password.com/docs/ssh/agent/advanced/#match-key-with-host
Host bitbucket.org
  IdentityFile ~/.ssh/juspay.pub
  IdentitiesOnly yes

Host *
  IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
```

### PR DESCRIPTION
**Pull request by LovingMelody**
This commit nixify's the .ssh/config using home-manager resolves #36

### CODE REVIEW

**Comment by srid** [comment]
Thanks! Works great. 

One thing I find strange is that after activating the home configuration, `~/.ssh/config` is nowhere to be found (even though it [should have been created](https://github.com/nix-community/home-manager/blob/21b078306a2ab68748abf72650db313d646cf2ca/modules/programs/ssh.nix#L521-L533)) - yet I can ssh to these hosts by their alias in the config. `/etc/ssh` doesn't contain my config either.

**Comment by srid** [comment]
Oh wait, ssh is probably using some other host cache (even across reboot of the mac). Settings like `ForwardAgent`, however, are not being used after this PR.

**Comment by srid** [comment]
Alright, we just need `programs.ssh.enable = true;`. 

For the record, I don't have permissions to push commits to your branch, so I'll open a new PR with additional commits of my own.

**Comment by LovingMelody** [comment]
I have added the requested changes, please adjust the ForwardAgent as you would like. 
Just as a note, identityAgent will require that 1password is installed unless you override it. You may wish to make 1password optional as a whole as I have done in [my config](https://gitlab.com/LovingMelody/configsreborn/-/blob/8caac5cf3a8eb87a63c9d875d34b80e0dd48df2f/src/modules/1password/homeModules/default.nix) but that is out of scope for this PR.

**Pull request merged**
